### ISSUE TITLE
.xml suffix for layout file

### ISSUE THREAD

**Issue by adamski** [audiokinematics/juceLayouts#3]
I think the custom suffix `.jui` is unnecessary and will usually mean that editors don't know it's XML and hence won't syntax highlight the file. 
I would suggest to keep it as `.xml`, so everyone knows what kind of file it is.

**Comment by ffAudio** [comment]
That's true. A special suffix makes only sense, if there is a special editor for that. I hoped it will be in the Introjucer workflow one time. But it is nowhere wired, only used in the example. There is no harm in using xml, and I will make sure not to employ any need for a certain suffix. Maybe I change it in the example as well...

**Comment by ffAudio** [comment]
...just pushed it. Thanks for the suggestion.
