### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by adamski** [audiokinematics/juceLayouts#4]
I would not name your module starting with `juce_` as I think that should be reserved for JUCE internal modules. Maybe start with just `ak_` as your namespace if you like. Just my opinion... 
Great work anyhow :+1:

**Comment by ffAudio** [comment]
You may have noticed, that I did not put it in the juce namespace, so I shouldn't get any conflicts. It's only the filenames and that's meant as a reference, where it is used. There are good reasons for both, I think for the moment I keep it that way. 
And thanks for the compliments :-)

**Comment by adamski** [comment]
Ok, but I see no reason to put `juce_` in front of the name. In contributing to the JPM project, there is a module search facility. I would expect, when searching for `juce` to get all the JUCE internal modules, not 3rd party modules. The general convention I see is to precede the module name with the namespace name. 
E.g. https://github.com/jcredland/juce-toys/tree/master/jcf_debug and https://github.com/adamski/RestRequest

**Comment by ffAudio** [comment]
You are right, it's misleading information. Just renamed it.
